name: CI

on:
  push:
    branches: [ main, develop, feature/* ]
    
jobs:
  build-ts-examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          cd examples/typescript
          yarn install --frozen-lockfile

      - name: Build
        run: |
          cd examples/typescript
          yarn build  

  docker-build-environments:
    runs-on: ubuntu-latest
    needs: build-ts-examples
    strategy:
      matrix:
        environment: [jupyter]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - id: filter
        uses: dorny/paths-filter@v2
        with:
          base: ${{ github.ref }}
          list-files: shell
          filters: |
            jupyter:
              - 'environments/jupyter/**'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
        # Only build image if there's a change in the folder
      - name: Build environment Docker image
        if: steps.filter.outputs[matrix.environment] == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./environments/${{ matrix.environment }}
          push: false